### ISSUE TITLE
Integrate GolangCi-Lint

### ISSUE THREAD

**Issue by hanzei** [mattermost/matterbuild#32]
Integrate `golangci-lint` into this repository. https://github.com/mattermost/mattermost-plugin-starter-template/blob/master/.golangci.yml should be used as a starting point for the configuration. https://circleci.com/orbs/registry/orb/gotest/tools is a good circleci orb on install `golangci-lint`.

`make check-style` should be changed to:
```make
## Checks code style.
.PHONY: check-style
check-style: golangci-lint
	@echo Checking for style guide compliance

## Run golangci-lint on codebase.
.PHONY: golangci-lint
golangci-lint:
	@if ! [ -x "$$(command -v golangci-lint)" ]; then \
		echo "golangci-lint is not installed. Please see https://github.com/golangci/golangci-lint#install for installation instructions."; \
		exit 1; \
	fi; \


	@echo Running golangci-lint
	golangci-lint run ./...
```

**Comment by AugustasV** [comment]
I would like to work on this one!

**Comment by hanzei** [comment]
Awesome, thanks @AugustasV :+1:

**Comment by AugustasV** [comment]
@hanzei I think as my PR was merged, this is good to close?

**Comment by hanzei** [comment]
@AugustasV Yes. Thanks for the reminder :+1:
